name: Validate

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

env:
  TEST_TAG: ${{ github.repository }}:test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-validate
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    name: Lint
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  type-check:
    runs-on: ubuntu-24.04
    name: Type Check
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn type-check

  unit_test:
    runs-on: ubuntu-24.04
    name: Unit Test
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn vitest --run --dir src

  integration_test:
    runs-on: ubuntu-24.04
    name: Integration Test
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn vitest --run --dir integration-tests

  smoke_test:
    runs-on: ubuntu-24.04
    name: Smoke test
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: scripts/local-smoke-test.sh

  docker_test:
    name: Smoke test on Docker container
    timeout-minutes: 5
    needs: smoke_test
    strategy:
      matrix:
        platform: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
          cache-from: type=gha,scope=global
          cache-to: type=gha,mode=max,scope=global

      - name: Get a free port
        run: echo "PORT=$(scripts/get-free-port.sh)" >> $GITHUB_ENV

      - name: Start the Docker container
        run: docker run -d --rm --name test-container -p ${{ env.PORT }}:9229 ${{ env.TEST_TAG }}

      - name: Test 
        run: scripts/smoke-test.sh
        env:
          PORT: ${{ env.PORT }}

      - name: Stop the Docker container
        run: docker stop test-container
